"""added member_id in cmte_sponsor_requests table

Revision ID: 0001ed10938d
Revises: e59ca82cca7b
Create Date: 2025-03-29 17:46:43.661988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001ed10938d'
down_revision = 'e59ca82cca7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_requests', sa.Column('member_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_sponsor_requests', 'cmte_sponsor_members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cmte_sponsor_requests', type_='foreignkey')
    op.drop_column('cmte_sponsor_requests', 'member_id')
    # ### end Alembic commands ###
