"""added some fields to the model

Revision ID: 040eff0d8f33
Revises: bf689abf5b46
Create Date: 2025-09-29 13:59:02.828515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040eff0d8f33'
down_revision = 'bf689abf5b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_group_participation_records', sa.Column('approved_date', sa.Date(), nullable=True))
    op.add_column('cmte_event_group_participation_records', sa.Column('closed_date', sa.Date(), nullable=True))
    op.add_column('cmte_event_group_participation_records', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_group_participation_records', 'reason')
    op.drop_column('cmte_event_group_participation_records', 'closed_date')
    op.drop_column('cmte_event_group_participation_records', 'approved_date')
    # ### end Alembic commands ###
