"""added LiceseRenewal model to accomodate advanced renewal

Revision ID: 08dbcb75e534
Revises: 0eab0483c955
Create Date: 2026-03-18 13:31:08.302000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08dbcb75e534'
down_revision = '0eab0483c955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_renewals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['license_number'], ['licenses.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license_renewals')
    # ### end Alembic commands ###
