"""added created_at column in cmte_sponsor_docs table

Revision ID: 0ce2a9dafa64
Revises: 7a760a4e2281
Create Date: 2025-03-07 21:45:53.606291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce2a9dafa64'
down_revision = '7a760a4e2281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_docs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_sponsor_docs', 'created_at')
    # ### end Alembic commands ###
