"""added the update datetime field to the address model

Revision ID: 0e38dcd3d898
Revises: 1fc469e6272d
Create Date: 2025-08-31 23:11:41.891095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e38dcd3d898'
down_revision = '1fc469e6272d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_addresses', sa.Column('updated_at', sa.DateTime(timezone=True),
                                                server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_addresses', 'updated_at')
    # ### end Alembic commands ###
