"""added activity_id field

Revision ID: 0eab0483c955
Revises: 881c33871622
Create Date: 2025-10-01 23:55:36.238553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eab0483c955'
down_revision = '881c33871622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_group_participation_records', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_event_group_participation_records', 'cmte_event_activities', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cmte_event_group_participation_records', type_='foreignkey')
    op.drop_column('cmte_event_group_participation_records', 'activity_id')
    # ### end Alembic commands ###
