"""deleted CMTETempSponsor table

Revision ID: 0f8c53aa3620
Revises: c162b1d230aa
Create Date: 2025-05-16 16:43:24.212144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f8c53aa3620'
down_revision = 'c162b1d230aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_sponsor_qualification_assoc')
    op.drop_table('cmte_temp_sponsors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_temp_sponsors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cmte_temp_sponsors_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('sponsor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('affiliation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zipcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telephone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('registered_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expire_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_detail', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('private_sector', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['cmte_event_sponsors.id'], name='cmte_temp_sponsors_sponsor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cmte_temp_sponsors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('temp_sponsor_qualification_assoc',
    sa.Column('event_sponsor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qualification_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_sponsor_id'], ['cmte_temp_sponsors.id'], name='temp_sponsor_qualification_assoc_event_sponsor_id_fkey'),
    sa.ForeignKeyConstraint(['qualification_id'], ['cmte_sponsor_qualification.id'], name='temp_sponsor_qualification_assoc_qualification_id_fkey')
    )
    # ### end Alembic commands ###
