"""added private_sector column in cmte_sponsor_qualification table

Revision ID: 11ea85a15572
Revises: 4bcb209f58c2
Create Date: 2025-03-15 09:41:53.072056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ea85a15572'
down_revision = '4bcb209f58c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_qualification', sa.Column('private_sector', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_sponsor_qualification', 'private_sector')
    # ### end Alembic commands ###
