"""added updated_at column in cmte_event_sponsors table

Revision ID: 13129cfccc99
Revises: 2061089475af
Create Date: 2025-07-02 20:57:18.430813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13129cfccc99'
down_revision = '2061089475af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_sponsors', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cmte_event_sponsors_version', sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_sponsors_version', 'updated_at')
    op.drop_column('cmte_event_sponsors', 'updated_at')
    # ### end Alembic commands ###
