"""added sponsor_qualification_assoc table for sponsor qualifications

Revision ID: 1e69a5955913
Revises: 5e5357f8a158
Create Date: 2025-02-08 16:38:03.649902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e69a5955913'
down_revision = '5e5357f8a158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor_qualification_assoc',
    sa.Column('event_sponsor_id', sa.Integer(), nullable=True),
    sa.Column('qualification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_sponsor_id'], ['cmte_event_sponsors.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['cmte_sponsor_qualification.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsor_qualification_assoc')
    # ### end Alembic commands ###
