"""added the address model

Revision ID: 1fc469e6272d
Revises: f71d0d8695ea
Create Date: 2025-08-31 23:05:06.002507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc469e6272d'
down_revision = 'f71d0d8695ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street_number', sa.String(), nullable=True),
    sa.Column('alley', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('address_type', sa.Integer(), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_addresses')
    # ### end Alembic commands ###
