"""deleted zipcode column in cmte_receipt_details table

Revision ID: 2061089475af
Revises: 59c2fb542f77
Create Date: 2025-06-29 19:05:37.535413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2061089475af'
down_revision = '59c2fb542f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_receipt_details', 'zipcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_receipt_details', sa.Column('zipcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
