"""added CMTEEventCode back again

Revision ID: 220102f72625
Revises: 2a896376bd83
Create Date: 2024-09-07 11:18:04.649135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220102f72625'
down_revision = '2a896376bd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_event_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmte_event_codes')
    # ### end Alembic commands ###
