"""added submission datetime field

Revision ID: 23286917f539
Revises: 13340d16f2bf
Create Date: 2024-04-20 07:53:43.605885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23286917f539'
down_revision = '13340d16f2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_events', sa.Column('submitted_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_events', 'submitted_datetime')
    # ### end Alembic commands ###
