"""added comment and payment approve datetime fields

Revision ID: 234cb1ae1c6f
Revises: 7b1bb2e87c0e
Create Date: 2025-05-23 10:56:43.640343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234cb1ae1c6f'
down_revision = '7b1bb2e87c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_events', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('cmte_events', sa.Column('payment_approve_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_events', 'payment_approve_datetime')
    op.drop_column('cmte_events', 'comment')
    # ### end Alembic commands ###
