"""added a note field

Revision ID: 24dcd185a267
Revises: 7ea6b508c206
Create Date: 2025-09-27 23:06:48.419271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dcd185a267'
down_revision = '7ea6b508c206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_participation_record_requests', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_participation_record_requests', 'note')
    # ### end Alembic commands ###
