"""added begin, end date and status fields for the member model

Revision ID: 25c434cf760f
Revises: 19303ad062f4
Create Date: 2024-11-07 09:42:47.130393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c434cf760f'
down_revision = '19303ad062f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('status', sa.String(), nullable=True))
    op.add_column('members', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('begin_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'begin_date')
    op.drop_column('members', 'end_date')
    op.drop_column('members', 'status')
    # ### end Alembic commands ###
