"""added CMTESponsorMember model

Revision ID: 2a2650176269
Revises: ce5ce15a3beb
Create Date: 2024-10-08 11:05:07.242619

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2a2650176269'
down_revision = 'ce5ce15a3beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_sponsor_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('_password_hash', sa.String(length=255), nullable=True),
    sa.Column('mobile_phone', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('is_coordinator', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['cmte_event_sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmte_sponsor_members')
    # ### end Alembic commands ###
