"""created cmte_renew_sponsor_requests table

Revision ID: 31c7f58e8403
Revises: 65aa6acbdf35
Create Date: 2025-02-22 18:00:19.375571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c7f58e8403'
down_revision = '65aa6acbdf35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_renew_sponsor_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['cmte_event_sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cmte_event_sponsors_version', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cmte_event_sponsors_version', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.drop_table('cmte_renew_sponsor_requests')
    # ### end Alembic commands ###
