"""added expire_date column in cmte_renew_sponsor_requests table

Revision ID: 397599a15147
Revises: 7aed3fbe0d22
Create Date: 2025-02-23 11:24:08.472496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397599a15147'
down_revision = '7aed3fbe0d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_renew_sponsor_requests', sa.Column('expire_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_renew_sponsor_requests', 'expire_date')
    # ### end Alembic commands ###
