"""added old ID field

Revision ID: 3d2d4c4524f9
Revises: 97d5377ad71b
Create Date: 2024-10-15 08:47:44.273341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2d4c4524f9'
down_revision = '97d5377ad71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_types', sa.Column('old_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_types', 'old_id')
    # ### end Alembic commands ###
