"""added payment datetime field

Revision ID: 3d7a072190c8
Revises: 8c06d64a2a1b
Create Date: 2024-05-23 23:10:48.590790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7a072190c8'
down_revision = '8c06d64a2a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_events', sa.Column('payment_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_events', 'payment_datetime')
    # ### end Alembic commands ###
