"""added company field

Revision ID: 41c4eb8e9084
Revises: 963a004aca1e
Create Date: 2023-04-03 06:51:14.849776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c4eb8e9084'
down_revision = '963a004aca1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'company')
    # ### end Alembic commands ###
