"""added submitted datetime to group records

Revision ID: 44d49fece782
Revises: dd8673a8f4d1
Create Date: 2026-06-05 12:04:25.133057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d49fece782'
down_revision = 'dd8673a8f4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_group_participation_records', sa.Column('submitted_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_group_participation_records', 'submitted_datetime')
    # ### end Alembic commands ###
