"""removed not null constraint

Revision ID: 48b060f347d7
Revises: fb4b2fef298e
Create Date: 2024-10-13 09:25:53.726929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b060f347d7'
down_revision = 'fb4b2fef298e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'en_firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'en_lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'en_lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'en_firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
