"""added association table for event types and fee rates

Revision ID: 4b5d308c4434
Revises: 23286917f539
Create Date: 2024-05-23 20:25:13.364630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5d308c4434'
down_revision = '23286917f539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_event_type_fee_assoc',
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('fee_rate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['cmte_event_types.id'], ),
    sa.ForeignKeyConstraint(['fee_rate_id'], ['cmte_event_fee_rates.id'], )
    )
    op.add_column('cmte_events', sa.Column('coord_name', sa.String(), nullable=True))
    op.add_column('cmte_events', sa.Column('coord_phone', sa.String(), nullable=True))
    op.add_column('cmte_events', sa.Column('coord_email', sa.String(), nullable=True))
    op.drop_constraint('cmte_events_fee_rate_id_fkey', 'cmte_events', type_='foreignkey')
    op.drop_column('cmte_events', 'fee_rate_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_events', sa.Column('fee_rate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cmte_events_fee_rate_id_fkey', 'cmte_events', 'cmte_event_fee_rates', ['fee_rate_id'], ['id'])
    op.drop_column('cmte_events', 'coord_email')
    op.drop_column('cmte_events', 'coord_phone')
    op.drop_column('cmte_events', 'coord_name')
    op.drop_table('cmte_event_type_fee_assoc')
    # ### end Alembic commands ###
