"""added private_sector column in cmte_event_sponsors table

Revision ID: 4bcb209f58c2
Revises: ef7ae3b86d01
Create Date: 2025-03-08 11:34:12.427811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcb209f58c2'
down_revision = 'ef7ae3b86d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_sponsors', sa.Column('private_sector', sa.Boolean(), nullable=True))
    op.add_column('cmte_event_sponsors_version', sa.Column('private_sector', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_sponsors_version', 'private_sector')
    op.drop_column('cmte_event_sponsors', 'private_sector')
    # ### end Alembic commands ###
