"""added registered datetime field

Revision ID: 4c2bd8ad7b9c
Revises: 2a2650176269
Create Date: 2024-10-08 15:11:52.248929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2bd8ad7b9c'
down_revision = '2a2650176269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_sponsors', sa.Column('registered_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_sponsors', 'registered_datetime')
    # ### end Alembic commands ###
