"""added issuer field to the MemberCertificate model

Revision ID: 4f2523158ee4
Revises: 77e20fa2c1d3
Create Date: 2026-04-10 06:29:31.685223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2523158ee4'
down_revision = '77e20fa2c1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_certificates', sa.Column('issuer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_certificates', 'issuer')
    # ### end Alembic commands ###
