"""added a note field to the payment record

Revision ID: 501a15e4db96
Revises: 9ba2968ed296
Create Date: 2024-11-19 11:12:09.648250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501a15e4db96'
down_revision = '9ba2968ed296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_fee_payment_records', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_fee_payment_records', 'note')
    # ### end Alembic commands ###
