"""added is_valid column in cmte_sponsor_members table

Revision ID: 53976394d0d0
Revises: fdad078cc895
Create Date: 2025-04-05 14:14:06.296263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53976394d0d0'
down_revision = 'fdad078cc895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_members', sa.Column('is_valid', sa.Boolean(), nullable=True))
    op.add_column('cmte_sponsor_members_version', sa.Column('is_valid', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_sponsor_members_version', 'is_valid')
    op.drop_column('cmte_sponsor_members', 'is_valid')
    # ### end Alembic commands ###
