"""added education record model

Revision ID: 5719255b8b82
Revises: 5a7c3d21e8f4
Create Date: 2026-04-08 16:24:01.226233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5719255b8b82'
down_revision = '5a7c3d21e8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_education_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('degree_level', sa.String(), nullable=True),
    sa.Column('degree_name', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('graduate_year', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_education_records')
    # ### end Alembic commands ###
