"""added deprecated field to some models

Revision ID: 5cc8529d71f6
Revises: fc632e1ec2d1
Create Date: 2025-02-09 05:33:40.889598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc8529d71f6'
down_revision = 'fc632e1ec2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_activities', sa.Column('deprecated', sa.Boolean(), nullable=True))
    op.add_column('cmte_event_types', sa.Column('deprecated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_types', 'deprecated')
    op.drop_column('cmte_event_activities', 'deprecated')
    # ### end Alembic commands ###
