"""created CMTESponsorQualification table

Revision ID: 5e5357f8a158
Revises: 45d0ec742dac
Create Date: 2025-02-08 16:27:01.755038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5357f8a158'
down_revision = '45d0ec742dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_sponsor_qualification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmte_sponsor_qualification')
    # ### end Alembic commands ###
