"""added updated_at column in cmte_sponsor_requests table

Revision ID: 5eb5e23731b1
Revises: cc1706dbc277
Create Date: 2025-06-25 22:33:11.899374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb5e23731b1'
down_revision = 'cc1706dbc277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_requests', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_sponsor_requests', 'updated_at')
    # ### end Alembic commands ###
