"""added a field to store a name of a participant submitted by a sponsor

Revision ID: 5f5ef41cd49b
Revises: f423b088f56b
Create Date: 2025-06-20 19:32:21.685381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5ef41cd49b'
down_revision = 'f423b088f56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_participation_records', sa.Column('submitted_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_participation_records', 'submitted_name')
    # ### end Alembic commands ###
