"""added a respond datetime field

Revision ID: 60aa6daf1964
Revises: 24dcd185a267
Create Date: 2025-09-27 23:09:31.903142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60aa6daf1964'
down_revision = '24dcd185a267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_participation_record_requests', sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_participation_record_requests', 'responded_at')
    # ### end Alembic commands ###
