"""added username and password fields

Revision ID: 660d14a4a74f
Revises: d1c2200bf9c8
Create Date: 2024-10-10 10:02:34.666969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660d14a4a74f'
down_revision = 'd1c2200bf9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('username', sa.String(), nullable=True))
    op.add_column('members', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'password')
    op.drop_column('members', 'username')
    # ### end Alembic commands ###
