"""added requester id field

Revision ID: 6b04a6df77b9
Revises: 5d4269d7dfb8
Create Date: 2025-09-26 09:23:29.567248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b04a6df77b9'
down_revision = '5d4269d7dfb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_participation_record_requests', sa.Column('requester', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_participation_record_requests', 'users', ['requester'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cmte_participation_record_requests', type_='foreignkey')
    op.drop_column('cmte_participation_record_requests', 'requester')
    # ### end Alembic commands ###
