"""added description field for the event type model

Revision ID: 6c083321c973
Revises: 9a6eec227d61
Create Date: 2024-07-27 09:12:54.201207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c083321c973'
down_revision = '9a6eec227d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_types', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_types', 'desc')
    # ### end Alembic commands ###
