"""added cmte point field

Revision ID: 6f24565ab79f
Revises: a2da0a36a6e9
Create Date: 2024-05-24 15:25:21.884608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f24565ab79f'
down_revision = 'a2da0a36a6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_events', sa.Column('cmte_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_events', 'cmte_points')
    # ### end Alembic commands ###
