"""added is_pending field for an event that needs more information for the admin

Revision ID: 712197e2d06d
Revises: 234cb1ae1c6f
Create Date: 2025-06-20 14:44:34.523829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712197e2d06d'
down_revision = '234cb1ae1c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_events', sa.Column('is_pending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_events', 'is_pending')
    # ### end Alembic commands ###
