"""replaced expire datetime field with expire date field

Revision ID: 7359d366c1aa
Revises: 4c2bd8ad7b9c
Create Date: 2024-10-08 16:40:51.509776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7359d366c1aa'
down_revision = '4c2bd8ad7b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_sponsors', sa.Column('expire_date', sa.Date(), nullable=True))
    op.drop_column('cmte_event_sponsors', 'expire_datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_sponsors', sa.Column('expire_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('cmte_event_sponsors', 'expire_date')
    # ### end Alembic commands ###
