"""added bill_name and receipt details columns in cmte_event_docs table

Revision ID: 7469af92aed9
Revises: e454212b10ae
Create Date: 2025-07-16 23:32:23.391174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7469af92aed9'
down_revision = 'e454212b10ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_docs', sa.Column('bill_name', sa.String(), nullable=True))
    op.add_column('cmte_event_docs', sa.Column('receipt_item', sa.Text(), nullable=True))
    op.add_column('cmte_event_docs', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('cmte_event_docs', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('cmte_event_docs', sa.Column('shipping_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_docs', 'shipping_address')
    op.drop_column('cmte_event_docs', 'address')
    op.drop_column('cmte_event_docs', 'tax_id')
    op.drop_column('cmte_event_docs', 'receipt_item')
    op.drop_column('cmte_event_docs', 'bill_name')
    # ### end Alembic commands ###
