"""added MemberCertificate and MemberExpertise model

Revision ID: 77e20fa2c1d3
Revises: 1e6a0d54f2ab
Create Date: 2026-04-10 06:12:01.341914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e20fa2c1d3'
down_revision = '1e6a0d54f2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('certificate_name', sa.String(), nullable=True),
    sa.Column('certificate_detail', sa.String(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('mtc_issued_date', sa.Date(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_expertise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expertise', sa.String(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_expertise')
    op.drop_table('member_certificates')
    # ### end Alembic commands ###
