"""deleted unverified column in cmte_sponsor_docs table

Revision ID: 7a760a4e2281
Revises: 15703cb31545
Create Date: 2025-03-07 21:41:08.103232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a760a4e2281'
down_revision = '15703cb31545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_sponsor_docs', 'unverified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_docs', sa.Column('unverified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
