"""added approved_at column in cmte_renew_sponsor_requests table

Revision ID: 7aed3fbe0d22
Revises: 31c7f58e8403
Create Date: 2025-02-22 21:10:41.746853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aed3fbe0d22'
down_revision = '31c7f58e8403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_renew_sponsor_requests', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_renew_sponsor_requests', 'approved_at')
    # ### end Alembic commands ###
