"""removed the relationship between event type and fee rates and added the relationship fee rates to the event activities

Revision ID: 7b1bb2e87c0e
Revises: 557434681083
Create Date: 2025-05-20 05:01:44.956826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1bb2e87c0e'
down_revision = '557434681083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_event_activity_fee_assoc',
    sa.Column('event_activity_id', sa.Integer(), nullable=True),
    sa.Column('fee_rate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_activity_id'], ['cmte_event_activities.id'], ),
    sa.ForeignKeyConstraint(['fee_rate_id'], ['cmte_event_fee_rates.id'], )
    )
    op.drop_table('cmte_event_type_fee_assoc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_event_type_fee_assoc',
    sa.Column('event_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fee_rate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['cmte_event_types.id'], name='cmte_event_type_fee_assoc_event_type_id_fkey'),
    sa.ForeignKeyConstraint(['fee_rate_id'], ['cmte_event_fee_rates.id'], name='cmte_event_type_fee_assoc_fee_rate_id_fkey')
    )
    op.drop_table('cmte_event_activity_fee_assoc')
    # ### end Alembic commands ###
