"""added close datetime field

Revision ID: 7ea6b508c206
Revises: 6b04a6df77b9
Create Date: 2025-09-27 22:52:37.861725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea6b508c206'
down_revision = '6b04a6df77b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_participation_record_requests', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_participation_record_requests', 'closed_at')
    # ### end Alembic commands ###
