"""added submission due date and other fields to Event and EventType model

Revision ID: 7f5f0dc9ed94
Revises: c0ddb236308d
Create Date: 2024-04-20 04:30:19.868153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5f0dc9ed94'
down_revision = 'c0ddb236308d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_types', sa.Column('submission_due', sa.Integer(), nullable=True))
    op.add_column('cmte_event_types', sa.Column('max_score', sa.Integer(), nullable=True))
    op.add_column('cmte_event_types', sa.Column('score_criteria', sa.String(), nullable=True))
    op.add_column('cmte_events', sa.Column('submission_due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_events', 'submission_due_date')
    op.drop_column('cmte_event_types', 'score_criteria')
    op.drop_column('cmte_event_types', 'max_score')
    op.drop_column('cmte_event_types', 'submission_due')
    # ### end Alembic commands ###
