"""added group submission only field

Revision ID: 84d8913776f3
Revises: 9cccf4e589c0
Create Date: 2025-02-09 10:17:08.469310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d8913776f3'
down_revision = '9cccf4e589c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_activities', sa.Column('group_submission_only', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_activities', 'group_submission_only')
    # ### end Alembic commands ###
