"""created cmte_receipt_details table

Revision ID: 84db52e1c5ca
Revises: d51bda809d58
Create Date: 2025-03-25 23:13:35.033473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84db52e1c5ca'
down_revision = 'd51bda809d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_receipt_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('receipt_item', sa.Text(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['cmte_event_sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('cmte_receipt_docs', 'name')
    op.drop_column('cmte_receipt_docs', 'tax_id')
    op.drop_column('cmte_receipt_docs', 'receipt_item')
    op.drop_column('cmte_receipt_docs', 'address')
    op.drop_column('cmte_receipt_docs', 'zipcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_receipt_docs', sa.Column('zipcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cmte_receipt_docs', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cmte_receipt_docs', sa.Column('receipt_item', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cmte_receipt_docs', sa.Column('tax_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cmte_receipt_docs', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('cmte_receipt_details')
    # ### end Alembic commands ###
