"""added a group record id field

Revision ID: 881c33871622
Revises: fd8df44f3832
Create Date: 2025-09-30 09:56:45.582422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881c33871622'
down_revision = 'fd8df44f3832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_docs', sa.Column('group_record_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_event_docs', 'cmte_event_group_participation_records', ['group_record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cmte_event_docs', type_='foreignkey')
    op.drop_column('cmte_event_docs', 'group_record_id')
    # ### end Alembic commands ###
