"""added create and update datetime fields

Revision ID: 890e56e37fbb
Revises: 5f67f05eab38
Create Date: 2025-02-09 06:40:48.346126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890e56e37fbb'
down_revision = '5f67f05eab38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_types', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cmte_event_types', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_types', 'updated_at')
    op.drop_column('cmte_event_types', 'created_at')
    # ### end Alembic commands ###
