"""added event activity model

Revision ID: 8a9a3b02f0d7
Revises: 3d2d4c4524f9
Create Date: 2024-10-15 08:56:18.180259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9a3b02f0d7'
down_revision = '3d2d4c4524f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_event_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('en_name', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['cmte_event_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmte_event_activities')
    # ### end Alembic commands ###
