"""added closed date and reason

Revision ID: 8b6de1dc98a1
Revises: 25c434cf760f
Create Date: 2024-11-19 09:05:44.306960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6de1dc98a1'
down_revision = '25c434cf760f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_participation_records', sa.Column('closed_date', sa.Date(), nullable=True))
    op.add_column('cmte_event_participation_records', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_participation_records', 'reason')
    op.drop_column('cmte_event_participation_records', 'closed_date')
    # ### end Alembic commands ###
