"""created cmte_sponsor_requests table

Revision ID: 92d05743b514
Revises: d22930caebc5
Create Date: 2025-02-23 12:45:10.288090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d05743b514'
down_revision = 'd22930caebc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_sponsor_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_sponsor_date', sa.Date(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['cmte_event_sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmte_sponsor_requests')
    # ### end Alembic commands ###
