"""added fee rate model

Revision ID: 94d0228be863
Revises: 93bba6883e34
Create Date: 2024-04-20 04:58:35.925806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d0228be863'
down_revision = '93bba6883e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_event_fee_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('fee_rate', sa.Numeric(), nullable=True),
    sa.Column('desc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cmte_events', sa.Column('fee_rate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_events', 'cmte_event_fee_rates', ['fee_rate_id'], ['id'])
    op.drop_column('cmte_events', 'max_participants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_events', sa.Column('max_participants', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cmte_events', type_='foreignkey')
    op.drop_column('cmte_events', 'fee_rate_id')
    op.drop_table('cmte_event_fee_rates')
    # ### end Alembic commands ###
