"""created qualification_id column in cmte_sponsor_docs table

Revision ID: 957dda6206fa
Revises: cd2b70f1af3d
Create Date: 2025-03-30 14:36:59.528130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957dda6206fa'
down_revision = 'cd2b70f1af3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_docs', sa.Column('qualification_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_sponsor_docs', 'cmte_sponsor_qualification', ['qualification_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cmte_sponsor_docs', type_='foreignkey')
    op.drop_column('cmte_sponsor_docs', 'qualification_id')
    # ### end Alembic commands ###
