"""added unique constraint to the name and email fields

Revision ID: 963a004aca1e
Revises: c7453b963b07
Create Date: 2023-04-03 06:49:52.681460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963a004aca1e'
down_revision = 'c7453b963b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'clients', ['email'])
    op.create_unique_constraint(None, 'clients', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    # ### end Alembic commands ###
