"""added old_user_id field

Revision ID: 97d5377ad71b
Revises: bef8b6851998
Create Date: 2024-10-15 07:27:34.605315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d5377ad71b'
down_revision = 'bef8b6851998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_members', sa.Column('old_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_sponsor_members', 'old_user_id')
    # ### end Alembic commands ###
