"""added is-sponsored field to the CMTE Event Type model

Revision ID: 9a368abd44db
Revises: 7921a73540a5
Create Date: 2024-04-20 04:09:16.745541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a368abd44db'
down_revision = '7921a73540a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_types', sa.Column('is_sponsored', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_types', 'is_sponsored')
    # ### end Alembic commands ###
