"""added score field to the CMTE record and replaced license id with license number field

Revision ID: 9a6eec227d61
Revises: f54de8cfab04
Create Date: 2024-07-26 21:44:41.656058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6eec227d61'
down_revision = 'f54de8cfab04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_participation_records', sa.Column('license_number', sa.String(), nullable=True))
    op.add_column('cmte_event_participation_records', sa.Column('score', sa.Numeric(), nullable=True))
    op.create_foreign_key(None, 'cmte_event_participation_records', 'licenses', ['license_number'], ['number'])
    op.drop_column('cmte_event_participation_records', 'license_id')
    op.drop_column('cmte_event_participation_records', 'title')
    op.drop_column('cmte_event_participation_records', 'middlename')
    op.drop_column('cmte_event_participation_records', 'lastname')
    op.drop_column('cmte_event_participation_records', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_participation_records', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cmte_event_participation_records', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cmte_event_participation_records', sa.Column('middlename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cmte_event_participation_records', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cmte_event_participation_records', sa.Column('license_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cmte_event_participation_records', type_='foreignkey')
    op.drop_column('cmte_event_participation_records', 'score')
    op.drop_column('cmte_event_participation_records', 'license_number')
    # ### end Alembic commands ###
