"""added number field

Revision ID: 9cccf4e589c0
Revises: 890e56e37fbb
Create Date: 2025-02-09 09:12:41.409409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cccf4e589c0'
down_revision = '890e56e37fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_activities', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('cmte_event_activities', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cmte_event_activities', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_activities', 'updated_at')
    op.drop_column('cmte_event_activities', 'created_at')
    op.drop_column('cmte_event_activities', 'number')
    # ### end Alembic commands ###
