"""added old_mem_id field to member model

Revision ID: a276732748f5
Revises: ec1142598f9a
Create Date: 2024-10-10 15:41:38.912951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a276732748f5'
down_revision = 'ec1142598f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('code', sa.String(), nullable=True))
    op.add_column('members', sa.Column('old_mem_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'old_mem_id')
    op.drop_column('members', 'code')
    # ### end Alembic commands ###
