"""added renew time field

Revision ID: a2da0a36a6e9
Revises: 614f6f676739
Create Date: 2024-05-24 08:20:18.433470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2da0a36a6e9'
down_revision = '614f6f676739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_events', sa.Column('renewed_times', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_events', 'renewed_times')
    # ### end Alembic commands ###
