"""added group submission allowed field to the event activity model

Revision ID: a962ebab8957
Revises: 5cc8529d71f6
Create Date: 2025-02-09 05:36:19.443745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a962ebab8957'
down_revision = '5cc8529d71f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_activities', sa.Column('group_submission_allowed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_activities', 'group_submission_allowed')
    # ### end Alembic commands ###
