"""added bill_name and receipt details columns in cmte_fee_payment_records table

Revision ID: afed4fe25d33
Revises: 8b5fccb20dda
Create Date: 2025-07-16 22:19:33.952819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afed4fe25d33'
down_revision = '8b5fccb20dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_fee_payment_records', sa.Column('bill_name', sa.String(), nullable=True))
    op.add_column('cmte_fee_payment_records', sa.Column('receipt_item', sa.Text(), nullable=True))
    op.add_column('cmte_fee_payment_records', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('cmte_fee_payment_records', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('cmte_fee_payment_records', sa.Column('shipping_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_fee_payment_records', 'shipping_address')
    op.drop_column('cmte_fee_payment_records', 'address')
    op.drop_column('cmte_fee_payment_records', 'tax_id')
    op.drop_column('cmte_fee_payment_records', 'receipt_item')
    op.drop_column('cmte_fee_payment_records', 'bill_name')
    # ### end Alembic commands ###
