"""added activity relationship

Revision ID: b104f3434c6b
Revises: 8a9a3b02f0d7
Create Date: 2024-10-15 09:23:42.933910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b104f3434c6b'
down_revision = '8a9a3b02f0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_events', sa.Column('old_id', sa.Integer(), nullable=True))
    op.add_column('cmte_events', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_events', 'cmte_event_activities', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cmte_events', type_='foreignkey')
    op.drop_column('cmte_events', 'activity_id')
    op.drop_column('cmte_events', 'old_id')
    # ### end Alembic commands ###
