"""removed unique constraint from members model

Revision ID: b208ebbfd7e9
Revises: 48b060f347d7
Create Date: 2024-10-15 05:31:10.372470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b208ebbfd7e9'
down_revision = '48b060f347d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('members_pid_key', 'members', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('members_pid_key', 'members', ['pid'])
    # ### end Alembic commands ###
