"""removed unique constraint from members model

Revision ID: b208ebbfd7e9
Revises: 48b060f347d7
Create Date: 2024-10-15 05:31:10.372470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b208ebbfd7e9'
down_revision = '48b060f347d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_index', table_name='member')
    op.drop_table('member')
    op.drop_constraint('members_pid_key', 'members', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('members_pid_key', 'members', ['pid'])
    op.create_table('member',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('old_mem_id', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('th_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('th_firstname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('th_lastname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('en_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('en_firstname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('en_lastname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('number', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_member_index', 'member', ['index'], unique=False)
    # ### end Alembic commands ###
