"""added event code field and table

Revision ID: b4d166e5ed46
Revises: 6c083321c973
Create Date: 2024-09-07 08:49:16.430660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d166e5ed46'
down_revision = '6c083321c973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_event_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cmte_events', sa.Column('event_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_events', 'event_code')
    op.drop_table('cmte_event_codes')
    # ### end Alembic commands ###
