"""added CMTE fee payment model

Revision ID: b5d44752742d
Revises: 220102f72625
Create Date: 2024-09-23 14:14:05.113864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5d44752742d'
down_revision = '220102f72625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_fee_payment_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['license_number'], ['licenses.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmte_fee_payment_records')
    # ### end Alembic commands ###
