"""removed unique restriction from email field

Revision ID: b61dcc64efd1
Revises: a276732748f5
Create Date: 2024-10-10 16:10:42.197173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61dcc64efd1'
down_revision = 'a276732748f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('members_email_key', 'members', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('members_email_key', 'members', ['email'])
    # ### end Alembic commands ###
