"""added default datetime for update datetime field in the member model

Revision ID: b757fc79f7b1
Revises: 0e38dcd3d898
Create Date: 2025-09-01 00:13:41.180146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b757fc79f7b1'
down_revision = '0e38dcd3d898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'updated_at')
    # ### end Alembic commands ###
