"""added participant update datetime field

Revision ID: b9e8e5bfe035
Revises: 5f5ef41cd49b
Create Date: 2025-06-21 05:06:23.824980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e8e5bfe035'
down_revision = '5f5ef41cd49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_events', sa.Column('participant_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_events', 'participant_updated_at')
    # ### end Alembic commands ###
