"""added new columns (email and website) in CMTEEventSponsor table

Revision ID: bd2c761f74aa
Revises: fc632e1ec2d1
Create Date: 2025-02-08 09:21:11.274501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2c761f74aa'
down_revision = 'fc632e1ec2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_sponsors', sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True))
    op.add_column('cmte_event_sponsors', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_sponsors', 'website')
    op.drop_column('cmte_event_sponsors', 'email')
    # ### end Alembic commands ###
