"""added some fields

Revision ID: bef8b6851998
Revises: b208ebbfd7e9
Create Date: 2024-10-15 06:59:54.143719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef8b6851998'
down_revision = 'b208ebbfd7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_sponsors', sa.Column('old_id', sa.Integer(), nullable=True))
    op.add_column('cmte_event_sponsors', sa.Column('code', sa.String()))
    op.add_column('cmte_event_sponsors', sa.Column('zipcode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_sponsors', 'zipcode')
    op.drop_column('cmte_event_sponsors', 'code')
    op.drop_column('cmte_event_sponsors', 'old_id')
    # ### end Alembic commands ###
