"""added a group participation record

Revision ID: bf689abf5b46
Revises: 60aa6daf1964
Create Date: 2025-09-29 13:55:59.395495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf689abf5b46'
down_revision = '60aa6daf1964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_event_group_participation_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('create_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cmte_event_participation_records', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_event_participation_records', 'cmte_event_group_participation_records', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cmte_event_participation_records', type_='foreignkey')
    op.drop_column('cmte_event_participation_records', 'group_id')
    op.drop_table('cmte_event_group_participation_records')
    # ### end Alembic commands ###
