"""added category model

Revision ID: c0ddb236308d
Revises: 9a368abd44db
Create Date: 2024-04-20 04:24:33.837349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ddb236308d'
down_revision = '9a368abd44db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_event_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('cmte_event_types', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_event_types', 'cmte_event_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cmte_event_types', type_='foreignkey')
    op.drop_column('cmte_event_types', 'category_id')
    op.drop_table('cmte_event_categories')
    # ### end Alembic commands ###
