"""created cmte_sponsor_docs table

Revision ID: c3136206827f
Revises: 92d05743b514
Create Date: 2025-02-25 21:58:19.068288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3136206827f'
down_revision = '92d05743b514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_sponsor_docs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('upload_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_payment_slip', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['cmte_event_sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmte_sponsor_docs')
    # ### end Alembic commands ###
