"""added activity ID field to the record

Revision ID: c8e50403018f
Revises: 501a15e4db96
Create Date: 2024-11-20 05:44:53.724610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e50403018f'
down_revision = '501a15e4db96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_participation_records', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_event_participation_records', 'cmte_event_activities', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cmte_event_participation_records', type_='foreignkey')
    op.drop_column('cmte_event_participation_records', 'activity_id')
    # ### end Alembic commands ###
