"""created has_med_tech column in cmte_event_sponsors table

Revision ID: cc1706dbc277
Revises: b9e8e5bfe035
Create Date: 2025-06-24 19:40:02.306879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1706dbc277'
down_revision = 'b9e8e5bfe035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_sponsors', sa.Column('has_med_tech', sa.Boolean(), nullable=True))
    op.add_column('cmte_event_sponsors_version', sa.Column('has_med_tech', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_sponsors_version', 'has_med_tech')
    op.drop_column('cmte_event_sponsors', 'has_med_tech')
    # ### end Alembic commands ###
