"""added is_active column in cmte_sponsor_members table

Revision ID: cd2b70f1af3d
Revises: 0001ed10938d
Create Date: 2025-03-29 18:05:07.098223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2b70f1af3d'
down_revision = '0001ed10938d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_members', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('cmte_sponsor_members_version', sa.Column('is_active', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_sponsor_members_version', 'is_active')
    op.drop_column('cmte_sponsor_members', 'is_active')
    # ### end Alembic commands ###
