"""added some fields to CMTE participation record model for individual score submission

Revision ID: d16a04b0f59e
Revises: 7359d366c1aa
Create Date: 2024-10-09 07:39:37.075555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16a04b0f59e'
down_revision = '7359d366c1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_docs', sa.Column('record_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_event_docs', 'cmte_event_participation_records', ['record_id'], ['id'])
    op.add_column('cmte_event_participation_records', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('cmte_event_participation_records', sa.Column('individual', sa.Boolean(), nullable=True))
    op.add_column('cmte_event_participation_records', sa.Column('event_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_event_participation_records', 'cmte_event_types', ['event_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cmte_event_participation_records', type_='foreignkey')
    op.drop_column('cmte_event_participation_records', 'event_type_id')
    op.drop_column('cmte_event_participation_records', 'individual')
    op.drop_column('cmte_event_participation_records', 'description')
    op.drop_constraint(None, 'cmte_event_docs', type_='foreignkey')
    op.drop_column('cmte_event_docs', 'record_id')
    # ### end Alembic commands ###
