"""added a field for checking if the doc is a payment slip

Revision ID: d1c2200bf9c8
Revises: 20fd868d768f
Create Date: 2024-10-09 10:13:04.525420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c2200bf9c8'
down_revision = '20fd868d768f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_docs', sa.Column('is_payment_slip', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_event_docs', 'is_payment_slip')
    # ### end Alembic commands ###
