"""deleted cmte_renew_sponsor_requests table

Revision ID: d22930caebc5
Revises: 397599a15147
Create Date: 2025-02-23 12:38:59.916889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd22930caebc5'
down_revision = '397599a15147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmte_renew_sponsor_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_renew_sponsor_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sponsor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expire_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['cmte_event_sponsors.id'], name='cmte_renew_sponsor_requests_sponsor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cmte_renew_sponsor_requests_pkey')
    )
    # ### end Alembic commands ###
