"""created columns in cmte_receipt_docs in table

Revision ID: d51bda809d58
Revises: d79d776c18f4
Create Date: 2025-03-25 22:41:04.947301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51bda809d58'
down_revision = 'd79d776c18f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_receipt_docs', sa.Column('name', sa.String(), nullable=True))
    op.add_column('cmte_receipt_docs', sa.Column('receipt_item', sa.Text(), nullable=True))
    op.add_column('cmte_receipt_docs', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('cmte_receipt_docs', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('cmte_receipt_docs', sa.Column('zipcode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_receipt_docs', 'zipcode')
    op.drop_column('cmte_receipt_docs', 'address')
    op.drop_column('cmte_receipt_docs', 'tax_id')
    op.drop_column('cmte_receipt_docs', 'receipt_item')
    op.drop_column('cmte_receipt_docs', 'name')
    # ### end Alembic commands ###
