"""added comment and rejected_at columns in cmte_sponsor_requests in table

Revision ID: db8ed93776b5
Revises: 11ea85a15572
Create Date: 2025-03-23 13:13:30.678623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8ed93776b5'
down_revision = '11ea85a15572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_requests', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('cmte_sponsor_requests', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_sponsor_requests', 'rejected_at')
    op.drop_column('cmte_sponsor_requests', 'comment')
    # ### end Alembic commands ###
