"""added the first license issue date field to the Member model

Revision ID: dd8673a8f4d1
Revises: 4f2523158ee4
Create Date: 2026-05-24 09:53:25.195073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8673a8f4d1'
down_revision = '4f2523158ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('first_license_issue_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'first_license_issue_date')
    # ### end Alembic commands ###
