"""added related models for CMTE

Revision ID: df43e25de94c
Revises: 41c4eb8e9084
Create Date: 2024-04-20 04:01:18.881183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df43e25de94c'
down_revision = '41c4eb8e9084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_event_formats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cmte_event_sponsors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cmte_event_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('for_group', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cmte_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('approved_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['cmte_event_types.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['cmte_events.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['cmte_event_sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmte_events')
    op.drop_table('cmte_event_types')
    op.drop_table('cmte_event_sponsors')
    op.drop_table('cmte_event_formats')
    # ### end Alembic commands ###
