"""deleted bill_name and receipt details columns in cmte_fee_payment_records table

Revision ID: e454212b10ae
Revises: afed4fe25d33
Create Date: 2025-07-16 22:34:06.346209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e454212b10ae'
down_revision = 'afed4fe25d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_fee_payment_records', 'bill_name')
    op.drop_column('cmte_fee_payment_records', 'address')
    op.drop_column('cmte_fee_payment_records', 'shipping_address')
    op.drop_column('cmte_fee_payment_records', 'receipt_item')
    op.drop_column('cmte_fee_payment_records', 'tax_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_fee_payment_records', sa.Column('tax_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cmte_fee_payment_records', sa.Column('receipt_item', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cmte_fee_payment_records', sa.Column('shipping_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cmte_fee_payment_records', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cmte_fee_payment_records', sa.Column('bill_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
