"""created cmte_temp_sponsors table

Revision ID: e59ca82cca7b
Revises: 84db52e1c5ca
Create Date: 2025-03-27 11:19:48.950647

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59ca82cca7b'
down_revision = '84db52e1c5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_temp_sponsors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('registered_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('type_detail', sa.String(), nullable=True),
    sa.Column('private_sector', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['cmte_event_sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_sponsor_qualification_assoc',
    sa.Column('event_sponsor_id', sa.Integer(), nullable=True),
    sa.Column('qualification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_sponsor_id'], ['cmte_temp_sponsors.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['cmte_sponsor_qualification.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_sponsor_qualification_assoc')
    op.drop_table('cmte_temp_sponsors')
    # ### end Alembic commands ###
