"""added number field to all profile related fields

Revision ID: ecbf22ed9da1
Revises: 4afedcb5a34a
Create Date: 2025-09-09 16:26:28.004108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbf22ed9da1'
down_revision = '4afedcb5a34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_degrees', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('candidate_experiences', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('candidate_job_positions', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('candidate_visions', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_visions', 'number')
    op.drop_column('candidate_job_positions', 'number')
    op.drop_column('candidate_experiences', 'number')
    op.drop_column('candidate_degrees', 'number')
    # ### end Alembic commands ###
