"""deleted created_at  column in cmte_sponsor_docs table

Revision ID: ef7ae3b86d01
Revises: 0ce2a9dafa64
Create Date: 2025-03-07 21:47:33.186838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef7ae3b86d01'
down_revision = '0ce2a9dafa64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_sponsor_docs', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_docs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
