"""added info_request field for additional info request from an admin

Revision ID: f423b088f56b
Revises: 712197e2d06d
Create Date: 2025-06-20 14:50:50.872313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f423b088f56b'
down_revision = '712197e2d06d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_events', sa.Column('info_request', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_events', 'info_request')
    # ### end Alembic commands ###
