"""added cancelled_at in cmte_sponsor_requests table

Revision ID: f60fd3a71fec
Revises: 0f8c53aa3620
Create Date: 2025-05-16 19:12:42.554256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60fd3a71fec'
down_revision = '0f8c53aa3620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_requests', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_sponsor_requests', 'cancelled_at')
    # ### end Alembic commands ###
