"""added email to the client model

Revision ID: f702a0113814
Revises: a8d126c26f10
Create Date: 2023-03-22 22:59:16.025785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f702a0113814'
down_revision = 'a8d126c26f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###
