"""added member add request model

Revision ID: f71d0d8695ea
Revises: 7469af92aed9
Create Date: 2025-07-23 17:30:06.284101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71d0d8695ea'
down_revision = '7469af92aed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmte_sponsor_member_add_requests_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('to_sponsor_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('member_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cancalled_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_cmte_sponsor_member_add_requests_version_end_transaction_id'), 'cmte_sponsor_member_add_requests_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_cmte_sponsor_member_add_requests_version_operation_type'), 'cmte_sponsor_member_add_requests_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_cmte_sponsor_member_add_requests_version_transaction_id'), 'cmte_sponsor_member_add_requests_version', ['transaction_id'], unique=False)
    op.create_table('cmte_sponsor_member_add_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('to_sponsor_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancalled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['cmte_sponsor_members.id'], ),
    sa.ForeignKeyConstraint(['to_sponsor_id'], ['cmte_event_sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmte_sponsor_member_add_requests')
    op.drop_index(op.f('ix_cmte_sponsor_member_add_requests_version_transaction_id'), table_name='cmte_sponsor_member_add_requests_version')
    op.drop_index(op.f('ix_cmte_sponsor_member_add_requests_version_operation_type'), table_name='cmte_sponsor_member_add_requests_version')
    op.drop_index(op.f('ix_cmte_sponsor_member_add_requests_version_end_transaction_id'), table_name='cmte_sponsor_member_add_requests_version')
    op.drop_table('cmte_sponsor_member_add_requests_version')
    # ### end Alembic commands ###
