"""moved is_online from event to fee rate model

Revision ID: fbff9a8d2929
Revises: 94d0228be863
Create Date: 2024-04-20 05:05:15.056832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbff9a8d2929'
down_revision = '94d0228be863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_event_fee_rates', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.drop_column('cmte_event_fee_rates', 'desc')
    op.drop_column('cmte_events', 'is_online')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_events', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('cmte_event_fee_rates', sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('cmte_event_fee_rates', 'is_online')
    # ### end Alembic commands ###
