"""added status field to the license model

Revision ID: fc632e1ec2d1
Revises: c8e50403018f
Create Date: 2024-12-06 11:04:54.142971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc632e1ec2d1'
down_revision = 'c8e50403018f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'status')
    # ### end Alembic commands ###
