"""added group_record_id field to the request model

Revision ID: fd8df44f3832
Revises: 040eff0d8f33
Create Date: 2025-09-29 17:15:23.344926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8df44f3832'
down_revision = '040eff0d8f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_participation_record_requests', sa.Column('group_record_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cmte_participation_record_requests', 'cmte_event_group_participation_records', ['group_record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cmte_participation_record_requests', type_='foreignkey')
    op.drop_column('cmte_participation_record_requests', 'group_record_id')
    # ### end Alembic commands ###
