"""deleted is_active column in cmte_sponsor_members table

Revision ID: fdad078cc895
Revises: 957dda6206fa
Create Date: 2025-04-05 14:11:36.550463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdad078cc895'
down_revision = '957dda6206fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmte_sponsor_members', 'is_active')
    op.drop_column('cmte_sponsor_members_version', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmte_sponsor_members_version', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('cmte_sponsor_members', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
